server:
  port: 8080
  shutdown: graceful

spring:
  # thymeleaf - layout 사용으로 인한 추가 설정.
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  devtools:
    livereload:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 60s # Server Shutdown wait time.
  application:
    name: demo
  #######################
  # 404 HttpStatus Handling
#  mvc:
#    dispatch-options-request: false
#  web:
#    resources:
#      add-mappings: true
  #######################
  jpa:
    hibernate:
      ddl-auto: create # h2 DB 연결 시만 사용.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true # H2 Console 사용 여부 (H2 Database UI로 제공 기능)
      path: /h2-console # H2 Console Path [example: http://localhost/h2-console]

logging:
  config: classpath:log4j2.yml

  #spring.mvc.throw-exception-if-no-handler-found=true
  #spring.web.resources.add-mappings=false